/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffOrderRouteImport } from './routes/staff-order'
import { Route as ServingRouteImport } from './routes/serving'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const StaffOrderRoute = StaffOrderRouteImport.update({
  id: '/staff-order',
  path: '/staff-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ServingRoute = ServingRouteImport.update({
  id: '/serving',
  path: '/serving',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/serving': typeof ServingRoute
  '/staff-order': typeof StaffOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/serving': typeof ServingRoute
  '/staff-order': typeof StaffOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/serving': typeof ServingRoute
  '/staff-order': typeof StaffOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/kitchen'
    | '/login'
    | '/serving'
    | '/staff-order'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/kitchen' | '/login' | '/serving' | '/staff-order'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/kitchen'
    | '/login'
    | '/serving'
    | '/staff-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  ServingRoute: typeof ServingRoute
  StaffOrderRoute: typeof StaffOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-order': {
      id: '/staff-order'
      path: '/staff-order'
      fullPath: '/staff-order'
      preLoaderRoute: typeof StaffOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serving': {
      id: '/serving'
      path: '/serving'
      fullPath: '/serving'
      preLoaderRoute: typeof ServingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  ServingRoute: ServingRoute,
  StaffOrderRoute: StaffOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
